import adsk.core, adsk.fusion, traceback

BIN_XY_TOLERANCE = 0.01
BIN_CORNER_FILLET_RADIUS = 0.4 - BIN_XY_TOLERANCE
BIN_WALL_THICKNESS = 0.24
BIN_LIP_CHAMFER = 0.12
BIN_CONNECTION_RECESS_DEPTH = 0.4
BIN_BODY_BOTTOM_THICKNESS = 0.1
BIN_BODY_CUTOUT_BOTTOM_FILLET_RADIUS = 0.2

BASE_TOTAL_HEIGHT = 0.5

DIMENSION_DEFAULT_WIDTH_UNIT = 4.2
DIMENSION_DEFAULT_HEIGHT_UNIT = 0.7